sudo: false
language: rust
script:
 - |
    cargo test -p scattering --verbose &&
    cargo test --verbose &&
    cargo build --verbose &&
    cargo doc --no-deps &&
    cargo doc -p scattering
after_success: sh scripts/travis-doc-upload.sh
cache:
 directories:
  - $HOME/.cargo
