sudo: false
language: rust
script:
 - |
    cargo test -p linalg --verbose &&
    cargo test -p scattering --verbose &&
    cargo test --verbose &&
    cargo build --verbose
after_success: sh scripts/travis-doc-upload.sh
cache:
 directories:
  - $HOME/.cargo
